name: Feature Addition Pull Request
description: Propose a new feature
title: "[Feature]: "
labels: [enhancement]
body:
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Name of the proposed feature.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the proposed feature.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have updated the documentation.
          required: true
        - label: I have added tests to cover my changes.
          required: true
